'use client'
import { Loader2, Search } from 'lucide-react'
import type { Equipment } from '@/lib/incident_engine'
export function SearchBar({value,onChange,onSearch,loading}:{value:string;onChange:(v:string)=>void;onSearch:()=>void;loading?:boolean}){return <div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={value} onChange={e=>onChange(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onSearch()} placeholder="Buscar equipo, IP o incidencia (ej. Router Core Sector A)" className="h-12 w-full rounded-xl border border-border bg-card pl-11 pr-4 text-sm outline-none focus:border-primary"/></div><button onClick={onSearch} disabled={loading} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-primary-foreground">{loading&&<Loader2 className="h-4 w-4 animate-spin"/>}{loading?'Buscando...':'Buscar'}</button></div>}
export function SearchExamples({onSelect}:{onSelect:(v:string)=>void}){return <div className="flex flex-wrap gap-2">{['Incidencias activas','Routers con advertencia','OLTs caídas','Historial de hoy'].map(x=><button key={x} onClick={()=>onSelect(x)} className="rounded-lg border border-border px-3 py-1.5 text-xs text-muted-foreground hover:border-primary hover:text-foreground">{x}</button>)}</div>}
export function NetworkSearch({results,expanded,onToggle}:{results:Equipment[];expanded:string|null;onToggle:(id:string)=>void}){if(!results.length)return <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Ejecuta una búsqueda para consultar la red.</div>;return <div className="grid gap-3">{results.map(e=><div key={e.id} className="rounded-xl border border-border bg-card p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{e.nombre}</p><p className="mt-1 text-xs text-muted-foreground">{e.tipo==='router'?'Router MikroTik':'OLT GPON'} · {e.ip}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${e.estado==='operativo'?'bg-emerald-400/10 text-emerald-400':e.estado==='advertencia'?'bg-amber-400/10 text-amber-400':'bg-red-400/10 text-red-400'}`}>{e.estado}</span></div><div className="mt-4 flex justify-between text-xs text-muted-foreground"><span>Latencia <b className="text-foreground">{e.latencia}ms</b></span><button onClick={()=>onToggle(e.id)} className="font-bold text-primary">{expanded===e.id?'Ocultar detalles':'Ver detalles'}</button></div>{expanded===e.id&&<div className="mt-4 grid grid-cols-3 gap-3 border-t border-border pt-4 text-xs"><span>Uptime<strong className="block text-foreground">{Math.round(e.uptime/24)} días</strong></span><span>Jitter<strong className="block text-foreground">{e.jitter}ms</strong></span><span>Pérdida<strong className="block text-foreground">{e.perdidaPaquetes}%</strong></span></div>}</div>)}</div>}
export function QuickAccess({onClick}:{onClick:(id:string)=>void}){return <div className="flex flex-wrap gap-3"><button onClick={()=>onClick('topology')} className="rounded-lg border border-border px-4 py-2 text-sm">Topología de red</button><button onClick={()=>onClick('alerts')} className="rounded-lg border border-border px-4 py-2 text-sm">Centro de alertas</button><button onClick={()=>onClick('kpis')} className="rounded-lg border border-border px-4 py-2 text-sm">Dashboard de KPIs</button></div>}
export function Header(){return <header className="border-b border-border"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary font-black text-primary-foreground">N</div><div><p className="font-bold">NetVista</p><p className="text-[11px] text-muted-foreground">Gestión FTTH / MikroTik</p></div></div><div className="flex items-center gap-2 text-xs text-emerald-400"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Red operativa</div></div></header>}
export function Footer(){return <footer className="border-t border-border py-6 text-center text-xs text-muted-foreground">NetVista — Sistema de Gestión FTTH/MikroTik</footer>}
export function SearchTitle(){return null}
export function SearchHint(){return null}
export function SearchDivider(){return null}
export function SearchIcon(){return null}
export function LoadingIcon(){return null}
export function SearchResultsCount(){return null}
export function SearchControls(){return null}
export function SearchEmpty(){return null}
export function SearchLoading(){return null}
export function SearchError(){return null}
